<?php
// $Id: xoops_version.php,v 1.3 2005/03/14 20:05:43 jsaucier Exp $
//  ------------------------------------------------------------------------ //
//                           Document Manager                                //
//            Copyright (c) 2004 Informatique Strategique IS                 //
//                  <http://www.infostrategique.com/>                        //
//  ------------------------------------------------------------------------ //
//  This program is free software; you can redistribute it and/or modify     //
//  it under the terms of the GNU General Public License as published by     //
//  the Free Software Foundation; either version 2 of the License, or        //
//  (at your option) any later version.                                      //
//                                                                           //
//  You may not change or alter any portion of this comment or credits       //
//  of supporting developers from this source code or any supporting         //
//  source code which is considered copyrighted (c) material of the          //
//  original comment or credit authors.                                      //
//                                                                           //
//  This program is distributed in the hope that it will be useful,          //
//  but WITHOUT ANY WARRANTY; without even the implied warranty of           //
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the            //
//  GNU General Public License for more details.                             //
//                                                                           //
//  You should have received a copy of the GNU General Public License        //
//  along with this program; if not, write to the Free Software              //
//  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307 USA //
//  ------------------------------------------------------------------------ //


// Global information
$modversion['name'] = _MI_DOCMANAGER_NAME;
$modversion['version'] = 1.1;
$modversion['description'] = _MI_DOCMANAGER_DESC;
$modversion['author'] = "Jeff Saucier";
$modversion['credits'] = "http://www.infostrategique.com";
$modversion['help'] = "docs/README";
$modversion['license'] = "GPL voir gpl.txt";
$modversion['official'] = 1;
$modversion['image'] = "images/docmanager_slogo.png";
$modversion['dirname'] = "docmanager";


// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = "sql/mysql.sql";
//$modversion['sqlfile']['postgresql'] = "sql/pgsql.sql";


// Tables created by sql file (without prefix!)
$modversion['tables'][0] = "docmanager_folders";
$modversion['tables'][1] = "docmanager_files";
$modversion['tables'][2] = "docmanager_configs";
$modversion['tables'][3] = "docmanager_rights";



// Admin things

$modversion['hasAdmin'] = 1;
$modversion['adminindex'] = "admin/index.php";
$modversion['adminmenu'] = "admin/menu.php";



// Menu
$modversion['hasMain'] = 1;


// Search
$modversion['hasSearch'] = 1;
$modversion['search']['file'] = "include/search.inc.php";
$modversion['search']['func'] = "docmanager_search";


// Templates
$modversion['templates'][1]['file'] = 'docmanager_index.html';
$modversion['templates'][1]['description'] = '';
$modversion['templates'][2]['file'] = 'docmanager_createfolder.html';
$modversion['templates'][2]['description'] = '';
$modversion['templates'][3]['file'] = 'docmanager_erasefolder.html';
$modversion['templates'][3]['description'] = '';
$modversion['templates'][4]['file'] = 'docmanager_modfolder.html';
$modversion['templates'][4]['description'] = '';
$modversion['templates'][5]['file'] = 'docmanager_createfile.html';
$modversion['templates'][5]['description'] = '';
$modversion['templates'][6]['file'] = 'docmanager_erasefile.html';
$modversion['templates'][6]['description'] = '';
$modversion['templates'][7]['file'] = 'docmanager_viewfile.html';
$modversion['templates'][7]['description'] = '';
$modversion['templates'][8]['file'] = 'docmanager_majfile.html';
$modversion['templates'][8]['description'] = '';
$modversion['templates'][9]['file'] = 'docmanager_modfile.html';
$modversion['templates'][9]['description'] = '';

?>
